export const FIGHT_ADD_LIST_REQUEST = 'FIGHT_ADD_LIST_REQUEST';
export const FIGHT_ADD_LIST_SUCCESS = 'FIGHT_ADD_LIST_SUCCESS';
export const FIGHT_ADD_LIST_FAIL = 'FIGHT_ADD_LIST_FAIL';

export const FIGHT_GET_LIST_REQUEST = 'FIGHT_GET_LIST_REQUEST';
export const FIGHT_GET_LIST_SUCCESS = 'FIGHT_GET_LIST_SUCCESS';
export const FIGHT_GET_LIST_FAIL = 'FIGHT_GET_LIST_FAIL';

export const FIGHT_RESULT_CREATE_REQUEST = 'FIGHT_RESULT_CREATE_REQUEST';
export const FIGHT_RESULT_CREATE_SUCCESS = 'FIGHT_RESULT_CREATE_SUCCESS';
export const FIGHT_RESULT_CREATE_FAIL = 'FIGHT_RESULT_CREATE_FAIL';

export const FIGHT_RESULT_LIST_REQUEST = 'FIGHT_RESULT_LIST_REQUEST';
export const FIGHT_RESULT_LIST_SUCCESS = 'FIGHT_RESULT_LIST_SUCCESS';
export const FIGHT_RESULT_LIST_FAIL = 'FIGHT_RESULT_LIST_FAIL';
