export const PLAYER_ADD_LIST_REQUEST = 'PLAYER_ADD_LIST_REQUEST';
export const PLAYER_ADD_LIST_SUCCESS = 'PLAYER_ADD_LIST_SUCCESS';
export const PLAYER_ADD_LIST_FAIL = 'PLAYER_ADD_LIST_FAIL';

export const PLAYER_GET_LIST_REQUEST = 'PLAYER_GET_LIST_REQUEST';
export const PLAYER_GET_LIST_SUCCESS = 'PLAYER_GET_LIST_SUCCESS';
export const PLAYER_GET_LIST_FAIL = 'PLAYER_GET_LIST_FAIL';

export const PLAYER_UPDATE_SCORE_REQUEST = 'PLAYER_UPDATE_SCORE_REQUEST';
export const PLAYER_UPDATE_SCORE_SUCCESS = 'PLAYER_UPDATE_SCORE_SUCCESS';
export const PLAYER_UPDATE_SCORE_FAIL = 'PLAYER_UPDATE_SCORE_FAIL';
