export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAIL = 'TEAM_CREATE_FAIL';

export const TEAM_TOP_REQUEST = 'TEAM_TOP_REQUEST';
export const TEAM_TOP_SUCCESS = 'TEAM_TOP_SUCCESS';
export const TEAM_TOP_FAIL = 'TEAM_TOP_FAIL';
